### ISSUE TITLE
Recommended approach for logging?

### ISSUE THREAD

**Issue by sfgeorge** [adhearsion/has-guarded-handlers#4]
Good day,

@kares is helping to develop some improvements to the has-guarded-handler gem that we plan to push to a PR soon.  They include detection of ConcurrencyError conditions that _should not_ occur under normal circumstances.

What would be the recommended method of introducing the concept of logging to this gem?  We're hesitant to reference `pb_logger`, `logger` or any other construct that would infer specific dependencies.

Wondering what thoughts are on the matter of having loosely-coupled logging.

Thanks very much!

**Comment by sfgeorge** [comment]
Two potential approaches we could take that I thought of.  I prefer option 2.  Thoughts?

1.) trigger `:log` events using HasGuardedHandlers itself

Allow consumers to optionally register and implement handlers for `:log` events however they choose.
Pro: Fits the HGH way of things
Con: Would be difficult to log events within methods like `trigger_handler` without the risk of infinite recursion

2.) Create and use an overridable hgh_logger NullObject

Using an approach similar to the pb_logger from Adhearsion 2.x & Punchblock 2, [provide a dummy logger object](https://github.com/adhearsion/punchblock/blob/v2.7.5/lib/punchblock/core_ext/ruby.rb#L3-L7) that can later be [overridden](https://github.com/adhearsion/adhearsion/blob/v2.6.2/lib/adhearsion/foundation/object.rb#L8-L11).

**Comment by sfgeorge** [comment]
@benlangfeld @bklang Any recommendations on how best to handling logging from within has-guarded-handlers?

**Comment by bklang** [comment]
My opinion: Option 2 is more conventional, the way I've seen it done in other libraries. That would be my vote.
